"""add_moderation_system

Revision ID: 26890a5efb8d
Revises: ce3b9a0243c8
Create Date: 2025-06-02 10:12:38.377055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26890a5efb8d'
down_revision: Union[str, None] = 'ce3b9a0243c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_moderations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='moderation_status_enum'), nullable=False),
    sa.Column('moderator_comment', sa.Text(), nullable=True),
    sa.Column('moderation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.drop_table('ad_moderation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_moderation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('moderator_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('moderation_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('ad_moderation_car_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ad_moderation_pkey')),
    sa.UniqueConstraint('car_id', name=op.f('ad_moderation_car_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('ad_moderations')
    # ### end Alembic commands ###
