"""update deals

Revision ID: 282eec3e3bec
Revises: 338802e86506
Create Date: 2025-05-31 05:19:07.314834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282eec3e3bec'
down_revision: Union[str, None] = '338802e86506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('initiator_id', sa.Integer(), nullable=False))
    op.add_column('deals', sa.Column('confirmed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deals', 'users', ['initiator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deals', 'users', ['confirmed_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'confirmed_by_id')
    op.drop_column('deals', 'initiator_id')
    # ### end Alembic commands ###
