"""update deal

Revision ID: 338802e86506
Revises: 68e6ef1f2981
Create Date: 2025-05-31 05:11:54.033614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338802e86506'
down_revision: Union[str, None] = '68e6ef1f2981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_deal_participants'), 'deals', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_deal_participants'), 'deals', ['car_id', 'seller_id', 'buyer_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
