"""update deals

Revision ID: 36bfb5dc6cc2
Revises: 282eec3e3bec
Create Date: 2025-05-31 05:28:45.585241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36bfb5dc6cc2'
down_revision: Union[str, None] = '282eec3e3bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deals_confirmed_by_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_initiator_id_fkey'), 'deals', type_='foreignkey')
    op.drop_column('deals', 'status')
    op.drop_column('deals', 'initiator_id')
    op.drop_column('deals', 'confirmed_by_id')
    op.drop_column('deals', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('confirmed_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('initiator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('status', postgresql.ENUM('pending', 'accepted', 'rejected', 'completed', 'cancelled', name='deal_status_enum'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('deals_initiator_id_fkey'), 'deals', 'users', ['initiator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('deals_confirmed_by_id_fkey'), 'deals', 'users', ['confirmed_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
