"""drop saved search

Revision ID: 49442ba79874
Revises: 9e7c69d128d9
Create Date: 2025-05-27 14:14:31.022441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49442ba79874'
down_revision: Union[str, None] = '9e7c69d128d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_searches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('saved_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved_searches_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='saved_searches_pkey')
    )
    # ### end Alembic commands ###
