"""empty message

Revision ID: 5c9e84b5d07c
Revises: 
Create Date: 2025-04-28 14:58:24.200844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9e84b5d07c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_brand_id'), 'models', ['brand_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_criteria', sa.JSON(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body_type', sa.Enum('sedan', 'hatchback', 'liftback', 'suv', 'crossover', 'coupe', 'convertible', 'wagon', 'minivan', 'van', 'pickup', 'roadster', 'limousine', 'targa', 'fastback', 'microcar', name='body_type_enum'), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('drive_type', sa.Enum('fwd', 'rwd', 'awd', 'fourwd', name='drive_type_enum'), nullable=False),
    sa.Column('transmission', sa.Enum('manual', 'automatic', 'cvt', 'robot', name='transmission_enum'), nullable=False),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'electric', 'hybrid', name='fuel_type_enum'), nullable=False),
    sa.Column('steering_side', sa.Enum('left', 'right', name='steering_side_enum'), nullable=False),
    sa.Column('car_condition', sa.Enum('new', 'used', 'after_repair', 'damaged', 'for_parts', name='car_condition_enum'), nullable=False),
    sa.Column('engine_capacity', sa.Float(), nullable=False),
    sa.Column('engine_power', sa.Integer(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('listing_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_is_sold'), 'cars', ['is_sold'], unique=False)
    op.create_index(op.f('ix_cars_listing_date'), 'cars', ['listing_date'], unique=False)
    op.create_index(op.f('ix_cars_model_id'), 'cars', ['model_id'], unique=False)
    op.create_index(op.f('ix_cars_price'), 'cars', ['price'], unique=False)
    op.create_index(op.f('ix_cars_user_id'), 'cars', ['user_id'], unique=False)
    op.create_index(op.f('ix_cars_uuid'), 'cars', ['uuid'], unique=True)
    op.create_index(op.f('ix_cars_year'), 'cars', ['year'], unique=False)
    op.create_table('ad_moderation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('moderator_comment', sa.Text(), nullable=True),
    sa.Column('moderation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_table('car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'car_id', name='uq_user_car')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'car_id', name='uq_user_car_review')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('price_history')
    op.drop_table('messages')
    op.drop_table('favorites')
    op.drop_table('car_images')
    op.drop_table('ad_moderation')
    op.drop_index(op.f('ix_cars_year'), table_name='cars')
    op.drop_index(op.f('ix_cars_uuid'), table_name='cars')
    op.drop_index(op.f('ix_cars_user_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_price'), table_name='cars')
    op.drop_index(op.f('ix_cars_model_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_listing_date'), table_name='cars')
    op.drop_index(op.f('ix_cars_is_sold'), table_name='cars')
    op.drop_table('cars')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_models_brand_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('brands')
    # ### end Alembic commands ###
