"""update review

Revision ID: 5d3779595fc7
Revises: 36bfb5dc6cc2
Create Date: 2025-05-31 05:45:12.525806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3779595fc7'
down_revision: Union[str, None] = '36bfb5dc6cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('deal_id', sa.Integer(), nullable=False))
    op.alter_column('reviews', 'review_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('uq_user_car_review'), 'reviews', type_='unique')
    op.create_unique_constraint('uq_deal_review', 'reviews', ['deal_id'])
    op.drop_constraint(op.f('reviews_car_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'deals', ['deal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_car_id_fkey'), 'reviews', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_deal_review', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_user_car_review'), 'reviews', ['user_id', 'car_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('reviews', 'review_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('reviews', 'deal_id')
    op.drop_column('reviews', 'seller_id')
    # ### end Alembic commands ###
