"""update review

Revision ID: 954bdfb4955a
Revises: b9d68901c776
Create Date: 2025-05-31 07:50:05.157688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954bdfb4955a'
down_revision: Union[str, None] = 'b9d68901c776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_reviews_uuid'), 'reviews', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_uuid'), table_name='reviews')
    op.drop_column('reviews', 'uuid')
    # ### end Alembic commands ###
