"""update reviews

Revision ID: a84b25b769be
Revises: update_review_ids
Create Date: 2025-05-31 08:03:37.765433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84b25b769be'
down_revision: Union[str, None] = 'update_review_ids'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_uuid', sa.UUID(), nullable=False))
    op.add_column('reviews', sa.Column('seller_uuid', sa.UUID(), nullable=False))
    op.add_column('reviews', sa.Column('deal_uuid', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_deal_review'), 'reviews', type_='unique')
    op.create_unique_constraint('uq_deal_uuid_review', 'reviews', ['deal_uuid'])
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_seller_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_deal_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['seller_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'deals', ['deal_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('reviews', 'deal_id')
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('deal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_deal_id_fkey'), 'reviews', 'deals', ['deal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_seller_id_fkey'), 'reviews', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_deal_uuid_review', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_deal_review'), 'reviews', ['deal_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('reviews', 'deal_uuid')
    op.drop_column('reviews', 'seller_uuid')
    op.drop_column('reviews', 'user_uuid')
    # ### end Alembic commands ###
